# Generated by Django 4.0.5 on 2022-06-22 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField()),
                ('endereco', models.TextField()),
                ('complemento', models.TextField(max_length=50)),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('uf', models.CharField(max_length=5)),
                ('numero', models.IntegerField()),
                ('descricao', models.TextField(max_length=100)),
                ('data_adicionado', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
